### ISSUE TITLE
Trace var is failing (Var cannot be cast to Named)

### ISSUE THREAD

**Issue by emkayonline** [technomancy/swank-clojure#102]
This problem is caused due to the first let in swank.commands.basic /trace-fn-call.  

This let isn't needed and when it is removed (and sum is renamed to frame) tracing works.  

Interestingly the line is commented in the source with:

 ;; what is the point of this?

Martin

**Comment by tavisrudd** [comment]
@emkayonline the "what is the point of this" comment was from me.  Looking at the code again now I see that only user of that function is actually passing in a var rather than a symbol as you would expect from the arg name.  So some conversion is required.  swank-toggle-trace was using the name 'sym' for a var.  untrace-all was also confused. I've just fixed all three.
