### ISSUE TITLE
Make swank-clojure part of slime project as contrib

### ISSUE THREAD

**Issue by markokocic** [technomancy/swank-clojure#13]
Making swank-clojure a slime contrib will make it easier to keep swank-clojure and slime in sync.
Right now being forced to use older version of slime and ELPA in order to use clojure is a pain, especially for regular Common Lisp users that already have perfectly working slime setup which should be shared for clojure too.

**Comment by technomancy** [comment]
Swank Clojure works with SLIME head now.

The Clojure parts of Swank Clojure will never be part of SLIME for a variety of reasons (we want to do real releases rather than a trickle-trunk; they use CVS, license conflicts, etc), but the elisp launcher part could some day become part of it if someone wants to head up that effort.
